### ISSUE TITLE
Exploration strategy

### ISSUE THREAD

**Issue by Crystal-Spider** [LucasAlegre/linear-rl#1]
I noticed that in this implementation of True Online SARSA, the epsilon, aka the exploration rate, is not updated during the decision process.

However, in the referenced paper, they talk about using an epsilon-greedy exploration strategy:  
![Screenshot_2024-02-15-19-07-05-58_e5d3893ac03954c6bb675ef2555b879b](https://github.com/LucasAlegre/linear-rl/assets/65339023/62ab14c2-3677-4b02-9bc0-78ab984d370a)

So I was wondering, why isn't the epsilon updated during learning?  
Thank you

**Comment by LucasAlegre** [comment]
For no particular reason. It is also common to use a fixed small value of epsilon (e.g., 0.05), instead of starting with a high value which is decreased during learning. This typically works best in domains where a lot of exploration is unnecessary.

**Comment by Crystal-Spider** [comment]
Oh okay, I didn't know, I've always seen epsilon-greedy employed in these kind of cases.

I was trying to apply this with SumoRL for a big intersection, and the model was immediately going into what I think to be a local minimum and basically kept some lanes always green and some others always red.

I thought I might help the model by exploring a lot initially, given the larger space, and gradually decreasing the exploration rate.

Unless you want to update this repo with something similar to your already existing EpsilonGreedy class in SumoRL, I guess I can just create a subclass and override the `get_action` method to employ an epsilon-greedy strategy.

Thanks!
